version: 2
updates:
  # Enable version updates for Golang dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
