version: "2"

run:
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/mattermost/mattermost-plugin-confluence

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US

  exclusions:
    presets:
      - comments
      - common-false-positives
      - std-error-handling

    rules:
      - path: server/manifest.go
        linters:
          - unused
      - path: server/configuration.go
        linters:
          - unused
      - path: _test\.go
        linters:
          - bodyclose
          - scopelint # https://github.com/kyoh86/scopelint/issues/4
