// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-confluence/server/service (interfaces: Store)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AtomicModify mocks base method.
func (m *MockStore) AtomicModify(arg0 string, arg1 func([]byte) ([]byte, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtomicModify", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtomicModify indicates an expected call of AtomicModify.
func (mr *MockStoreMockRecorder) AtomicModify(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtomicModify", reflect.TypeOf((*MockStore)(nil).AtomicModify), arg0, arg1)
}
